In [1]:
import sys
sys.path.append('../')

In [2]:
import numpy as np, pandas as pd
from glob import glob
import shutil, os
import pickle
import matplotlib.pyplot as plt
import torch.nn.functional as F
from sklearn.model_selection import GroupKFold
from sklearn.decomposition import IncrementalPCA
from tqdm.notebook import tqdm
import seaborn as sns
import PIL.Image as Image
import torch
from torch.utils.data import Dataset, DataLoader
import cv2
import gc
import time
import pandas_profiling as pdp
from pathlib import Path
from sklearn.model_selection import StratifiedKFold
from utils.util import *
from utils.losses import *
import torch.nn as nn
import transformers as T
import albumentations
import pandas as pd
import cv2
import numpy as np
import timm
import torch.nn as nn
from sklearn import metrics
import torch
from tez.callbacks import EarlyStopping
from tqdm import tqdm
import math
import tez
import torch.optim as optim
import warnings
warnings.simplefilter('ignore')

In [3]:
class CONFIG:
    DATA_PATH = Path('../input/petfinder-pawpularity-score')
    OUTPUT_DIR = Path('../output/5')
    MODEL_DIR = Path('../models/swin_large_patch4_window12_384')
    MODEL_NAME = 'swin_large_patch4_window12_384'
    batch_size = 8
    image_size = 384
    fold = 5
    epoch = 20
    lr = 2e-4
    device='cuda'
    training_step=True
    pretrained=False
    SEED=42
if not os.path.isdir(CONFIG.OUTPUT_DIR):
    os.makedirs(CONFIG.OUTPUT_DIR)
LOGGER = init_logger(OUTPUT_DIR=CONFIG.OUTPUT_DIR)
fix_seed(CONFIG.SEED)

In [4]:
train_df = pd.read_csv(CONFIG.DATA_PATH / 'train.csv')
train_df['path'] = train_df['Id'].map(lambda x:str(CONFIG.DATA_PATH/'train'/x)+'.jpg')
train_df['image_size'] = train_df['path'].apply(lambda image_id : Image.open(image_id).size)
train_df['width'] = train_df['image_size'].apply(lambda x: x[0])
train_df['height'] = train_df['image_size'].apply(lambda x: x[1])

test_df = pd.read_csv(CONFIG.DATA_PATH / 'test.csv')
test_df['path'] = test_df['Id'].map(lambda x:str(CONFIG.DATA_PATH/'test'/x)+'.jpg')
test_df['image_size'] = test_df['path'].apply(lambda image_id : Image.open(image_id).size)
test_df['width'] = test_df['image_size'].apply(lambda x: x[0])
test_df['height'] = test_df['image_size'].apply(lambda x: x[1])

train_df.head()

Id  Subject Focus  Eyes  Face  Near  Action  \
0  0007de18844b0dbbb5e1f607da0606e0              0     1     1     1       0   
1  0009c66b9439883ba2750fb825e1d7db              0     1     1     0       0   
2  0013fd999caf9a3efe1352ca1b0d937e              0     1     1     1       0   
3  0018df346ac9c1d8413cfcc888ca8246              0     1     1     1       0   
4  001dc955e10590d3ca4673f034feeef2              0     0     0     1       0   

   Accessory  Group  Collage  Human  Occlusion  Info  Blur  Pawpularity  \
0          0      1        0      0          0     0     0           63   
1          0      0        0      0          0     0     0           42   
2          0      0        0      1          1     0     0           28   
3          0      0        0      0          0     0     0           15   
4          0      1        0      0          0     0     0           72   

                                                path   image_size  width  \
0  ../input/petfinder-pawpularity-score/train/000...   (405, 720)    405   
1  ../input/petfinder-pawpularity-score/train/000...  (1032, 774)   1032   
2  ../input/petfinder-pawpularity-score/train/001...   (720, 960)    720   
3  ../input/petfinder-pawpularity-score/train/001...   (405, 720)    405   
4  ../input/petfinder-pawpularity-score/train/001...   (540, 960)    540   

   height  
0     720  
1     774  
2     960  
3     720  
4     960

In [5]:
train_df = get_train_data(train_df, train_df['Pawpularity'], n_splits = CONFIG.fold, regression=True)

In [6]:
train_aug = albumentations.Compose(
    [
        albumentations.Resize(CONFIG.image_size, CONFIG.image_size, p=1),
        albumentations.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225],
            max_pixel_value=255.0,
            p=1.0,
        ),
    ],
    p=1.0,
)

In [7]:
class PawpularDataset:
    def __init__(self, df, dense_features, targets, augmentations):
        self.image_paths = df['path'].tolist()
        self.dense_features = dense_features
        self.targets = targets
        if self.targets is None:
            self.targets = torch.ones(len(self.image_paths))
        self.augmentations = augmentations
        
    def __len__(self):
        return len(self.image_paths)
    
    def __getitem__(self, item):
        image = cv2.imread(self.image_paths[item])
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        
        if self.augmentations is not None:
            augmented = self.augmentations(image=image)
            image = augmented["image"]
        targets = self.targets[item]
        image = np.transpose(image, (2, 0, 1)).astype(np.float32)
        
        features = self.dense_features[item, :]
        
        return {
            "image": torch.tensor(image, dtype=torch.float),
            "features": torch.tensor(features, dtype=torch.float),
            "targets": torch.tensor(targets, dtype=torch.float)
        }

In [15]:
class efficientnet_b0(nn.Module):
    def __init__(self,class_num):
        super().__init__()
        self.model = timm.create_model('efficientnet_b0', pretrained=True, in_chans=3)
        self.model.classifier = nn.Linear(self.model.classifier.in_features, 128)
        self.dropout = nn.Dropout(0.1)
        self.dense = nn.Linear(128
                               , class_num)

    def forward(self, image):
        x = self.model(image)
        x = self.dropout(x)
        x = self.dense(x)
        return x.squeeze(1)
class PawpularModel(nn.Module):
    def __init__(self, pet_classify_model, model_name):
        super().__init__()
        self.model = timm.create_model(model_name, pretrained=CONFIG.pretrained, in_chans=3)
        self.pet_classify_model = pet_classify_model
        self.model.head = nn.Linear(self.model.head.in_features, 128)
        self.dropout = nn.Dropout(0.1)
        self.dense1 = nn.Linear(140, 64)
        self.dense2 = nn.Linear(64, 1)

    def forward(self, image, features):
        x_ = self.model(image)
        x = self.dropout(x_)
        x = torch.cat([x, features], dim=1)
        x = self.dense1(x)
        x = self.dense2(x)
        p = F.softmax(self.pet_classify_model(F.adaptive_avg_pool2d(image, (224,224))), dim=1)
        return torch.cat([x, x_, features, p], axis=1)

In [16]:
def extraxt_feature(loader, extraxt_model, device):
    start = end = time.time()
    losses = AverageMeter()
    extraxt_model.eval()
    ex_feature = []
    for iter, data in tqdm(enumerate(loader), total=len(loader)):
        img, feature ,target = data['image'], data['features'], data['targets']
        img = img.to(device)
        feature = feature.to(device)
        target = target.to(device)
        with torch.no_grad():
            feature = extraxt_model(img, feature)
        ex_feature.append(feature)

    return torch.cat(ex_feature, axis=0)

In [17]:
def extract_loop(train, fold_):
    # ====================================================
    # Data Loader
    # ====================================================
    cl_model = efficientnet_b0(class_num=37)
    cl_model.to(CONFIG.device)
    cl_model.load_state_dict(fix_model_state_dict(torch.load('../input/The-Oxford-IIIT-Pet-Dataset/efficientnet_b0_Oxford_classifier_size_224.pth')["model"]))
    model = PawpularModel(pet_classify_model=cl_model, model_name=CONFIG.MODEL_NAME)
    model.to(CONFIG.device)
    cl_model=None
    gc.collect()
    if torch.cuda.device_count()>1:
        model=nn.DataParallel(model)
        model.load_state_dict(torch.load(CONFIG.MODEL_DIR / f"{CONFIG.MODEL_NAME}_{fold_}_best.pth")["model"],strict=False)
    else:
        model.load_state_dict(fix_model_state_dict(torch.load(CONFIG.MODEL_DIR / f"{CONFIG.MODEL_NAME}_{fold_}_best.pth")["model"]),strict=False)
    
    model.eval()    
    dense_features = [
        'Subject Focus', 'Eyes', 'Face', 'Near', 'Action', 'Accessory',
        'Group', 'Collage', 'Human', 'Occlusion', 'Info', 'Blur'
    ]
    pet_category = ['Abyssinian', 'Bengal', 'Birman', 'Bombay', 'British_Shorthair',
 'Egyptian_Mau' ,'Maine_Coon', 'Persian', 'Ragdoll', 'Russian_Blue' ,'Siamese',
 'Sphynx', 'american_bulldog' ,'american_pit_bull_terrier', 'basset_hound',
 'beagle', 'boxer' ,'chihuahua', 'english_cocker_spaniel', 'english_setter',
 'german_shorthaired' ,'great_pyrenees', 'havanese', 'japanese_chin',
 'keeshond', 'leonberger', 'miniature_pinscher', 'newfoundland', 'pomeranian',
 'pug' ,'saint_bernard' ,'samoyed' ,'scottish_terrier', 'shiba_inu',
 'staffordshire_bull_terrier' ,'wheaten_terrier' ,'yorkshire_terrier']
    
    val_idx = train[train.fold ==fold_].index
    valid_folds = train.loc[val_idx].reset_index(drop=True)
    
    val_dataset = PawpularDataset(
        valid_folds, 
        dense_features=valid_folds[dense_features].values, targets=valid_folds['Pawpularity']/100,
        augmentations=train_aug,
    )

    valid_loader = DataLoader(
        val_dataset,
        batch_size=CONFIG.batch_size,
        shuffle=False,
        pin_memory=True,
        drop_last=False,
    )
    
    # extract_feature
    feature = extraxt_feature(valid_loader, model,CONFIG.device)

    valid_folds[[f"embbeding_{CONFIG.MODEL_NAME}_{i}" for i in range(feature.shape[1])][:-len(pet_category)]+pet_category] = feature.data.cpu() 

    return valid_folds


In [18]:
def get_result(result_df):
    metric = RMSE()
    preds = result_df["Pawpularity"].values
    labels = result_df["preds"].values
    score = metric(preds, labels)
    LOGGER.info(f"Score: {score:<.5f}")

In [19]:
def inference():
    predictions = []
    dense_features = [
        'Subject Focus', 'Eyes', 'Face', 'Near', 'Action', 'Accessory',
        'Group', 'Collage', 'Human', 'Occlusion', 'Info', 'Blur'
    ]
    test_dataset = PawpularDataset(
        test_df, 
        dense_features=test_df[dense_features].values, targets=None,
        augmentations=train_aug,
    )
    test_loader = DataLoader(
        test_dataset, batch_size=16, shuffle=False, num_workers=4, pin_memory=True
    )
    features = []
    for fold_ in range(5):
        cl_model = efficientnet_b0(class_num=37)
        cl_model.to(CONFIG.device)
        cl_model.load_state_dict(fix_model_state_dict(torch.load('../input/The-Oxford-IIIT-Pet-Dataset/efficientnet_b0_Oxford_classifier_size_224.pth')["model"]))
        model = PawpularModel(pet_classify_model=cl_model, model_name=CONFIG.MODEL_NAME)
        model.to(CONFIG.device)
        cl_model=None
        gc.collect()
        if torch.cuda.device_count()>1:
            model=nn.DataParallel(model)
            model.load_state_dict(torch.load(CONFIG.MODEL_DIR / f"{CONFIG.MODEL_NAME}_{fold_}_best.pth")["model"],strict=False)
        else:
            model.load_state_dict(fix_model_state_dict(torch.load(CONFIG.MODEL_DIR / f"{CONFIG.MODEL_NAME}_{fold_}_best.pth")["model"]),strict=False)
        model.eval()
        ex_feature = []
        for iter, data in tqdm(enumerate(test_loader), total=len(test_loader)):
            img, feature ,target = data['image'], data['features'], data['targets']
            img = img.to(CONFIG.device)
            feature = feature.to(CONFIG.device)
            target = target.to(CONFIG.device)
            with torch.no_grad():
                feature = model(img, feature)
            ex_feature.append(feature.data.cpu())
        ex_feature = np.concatenate(ex_feature)
        features.append(ex_feature)
    feature = np.mean(np.stack(features, axis=0), axis=0)
    return feature

In [20]:
def main():
    # Training
    oof_df = pd.DataFrame()
    if CONFIG.training_step:
        for fold in range(CONFIG.fold):
            ex_ = extract_loop(train_df, fold)
            oof_df = pd.concat([oof_df, ex_])
        # Save OOF result
        oof_df.to_csv(CONFIG.OUTPUT_DIR / "oof_df.csv", index=False)
    else:
        oof_df = pd.read_csv(CONFIG.OUTPUT_DIR / "oof_df.csv")
    # CV result
    # Inference
    feature = inference()
    # submission
    pet_category = ['Abyssinian', 'Bengal', 'Birman', 'Bombay', 'British_Shorthair',
 'Egyptian_Mau' ,'Maine_Coon', 'Persian', 'Ragdoll', 'Russian_Blue' ,'Siamese',
 'Sphynx', 'american_bulldog' ,'american_pit_bull_terrier', 'basset_hound',
 'beagle', 'boxer' ,'chihuahua', 'english_cocker_spaniel', 'english_setter',
 'german_shorthaired' ,'great_pyrenees', 'havanese', 'japanese_chin',
 'keeshond', 'leonberger', 'miniature_pinscher', 'newfoundland', 'pomeranian',
 'pug' ,'saint_bernard' ,'samoyed' ,'scottish_terrier', 'shiba_inu',
 'staffordshire_bull_terrier' ,'wheaten_terrier' ,'yorkshire_terrier']
    test_feature = test_df.copy()
    test_feature[[f"embbeding_{CONFIG.MODEL_NAME}_{i}" for i in range(feature.shape[1])][:-len(pet_category)]+pet_category] = feature 
    return oof_df, test_feature

In [21]:
train_df, test_df = main()

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.75it/s]


In [22]:
 pet_category = ['Abyssinian', 'Bengal', 'Birman', 'Bombay', 'British_Shorthair',
 'Egyptian_Mau' ,'Maine_Coon', 'Persian', 'Ragdoll', 'Russian_Blue' ,'Siamese',
 'Sphynx', 'american_bulldog' ,'american_pit_bull_terrier', 'basset_hound',
 'beagle', 'boxer' ,'chihuahua', 'english_cocker_spaniel', 'english_setter',
 'german_shorthaired' ,'great_pyrenees', 'havanese', 'japanese_chin',
 'keeshond', 'leonberger', 'miniature_pinscher', 'newfoundland', 'pomeranian',
 'pug' ,'saint_bernard' ,'samoyed' ,'scottish_terrier', 'shiba_inu',
 'staffordshire_bull_terrier' ,'wheaten_terrier' ,'yorkshire_terrier']

In [41]:
pd.set_option('max_columns', 300)
train_df

Id  Subject Focus  Eyes  Face  Near  \
0     0049cb81313c94fa007286e9039af910              0     1     1     1   
1     005017716086b8d5e118dd9fe26459b1              0     1     1     1   
2     006483b96ca9c09b7afed3e3d3af539d              0     1     1     1   
3     00655425c10d4c082dd7eeb97fa4fb17              0     1     0     0   
4     0085bfb9a7ebfd776cb804d8b456bb05              0     1     1     1   
...                                ...            ...   ...   ...   ...   
1977  feea17136272d560dbaf5de9822bbe38              0     0     0     1   
1978  ff31c2bc7cf296899ce28a809600e20e              0     1     1     1   
1979  ff6bd913df168371937cfd31e01c058d              0     0     1     1   
1980  ffb8b466494a3e48bcb874a2fe9b976d              0     1     1     1   
1981  fff19e2ce11718548fa1c5d039a5192a              0     1     1     1   

      Action  Accessory  Group  Collage  Human  Occlusion  Info  Blur  \
0          0          0      0        0      0          0     0     0   
1          0          0      0        0      0          0     0     0   
2          0          0      0        0      1          1     0     0   
3          0          1      0        0      0          0     0     0   
4          0          0      0        0      0          0     0     0   
...      ...        ...    ...      ...    ...        ...   ...   ...   
1977       0          0      0        0      0          0     0     0   
1978       0          0      1        0      0          0     0     0   
1979       0          0      0        0      0          0     0     1   
1980       0          0      0        0      0          0     0     0   
1981       0          0      0        0      1          0     0     0   

      Pawpularity                                               path  \
0              21  ../input/petfinder-pawpularity-score/train/004...   
1              28  ../input/petfinder-pawpularity-score/train/005...   
2              41  ../input/petfinder-pawpularity-score/train/006...   
3              13  ../input/petfinder-pawpularity-score/train/006...   
4              50  ../input/petfinder-pawpularity-score/train/008...   
...           ...                                                ...   
1977           22  ../input/petfinder-pawpularity-score/train/fee...   
1978           46  ../input/petfinder-pawpularity-score/train/ff3...   
1979           44  ../input/petfinder-pawpularity-score/train/ff6...   
1980           31  ../input/petfinder-pawpularity-score/train/ffb...   
1981           20  ../input/petfinder-pawpularity-score/train/fff...   

        image_size  width  height  fold  \
0      (1279, 847)   1279     847     0   
1     (1280, 1280)   1280    1280     0   
2       (720, 960)    720     960     0   
3       (581, 638)    581     638     0   
4       (720, 960)    720     960     0   
...            ...    ...     ...   ...   
1977    (719, 959)    719     959     4   
1978    (720, 960)    720     960     4   
1979    (720, 960)    720     960     4   
1980    (925, 531)    925     531     4   
1981    (720, 960)    720     960     4   

      embbeding_swin_large_patch4_window12_384_0  \
0                                      -0.986894   
1                                      -0.532152   
2                                      -0.324362   
3                                      -0.742241   
4                                      -0.564538   
...                                          ...   
1977                                   -0.717110   
1978                                   -1.016717   
1979                                   -0.150923   
1980                                   -0.441537   
1981                                   -0.404671   

      embbeding_swin_large_patch4_window12_384_1  \
0                                      -0.082260   
1                                      -0.007847   
2                                      -0.100855   
3                                      -0.1

In [53]:
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.decomposition import PCA
X_train, y_train = train_df.drop(columns=['Id', 'path', 'Pawpularity', 'image_size']), train_df['Pawpularity']
CV = []
ts = PCA(n_components=10)
def rmse(pred, target):
    pred = np.array(pred)
    target = np.array(target)
    score = np.sqrt((np.mean((pred - target)**2)))
    return score
for fold in range(5):
    X_tr, y_tr = X_train[X_train.fold!=fold].drop(columns=['fold']).values, y_train[X_train.fold!=fold].values
    X_val, y_val = X_train[X_train.fold==fold].drop(columns=['fold']).values, y_train[X_train.fold==fold].values
    regr = make_pipeline(ts,SVR(C=20))
    print(y_val)
    regr.fit(X_tr, y_tr)
    pred = regr.predict(X_val)
    print(pred)
    score = rmse(pred, y_val)
    print(score)
    CV.append(score)
print(f'CV::::{sum(CV)/len(CV)}')

[21 28 41 ... 18 20 30]
[32.24213514 32.15947636 34.36980533 ... 34.22171855 32.87590945
 33.93257232]
21.006474055343176
[34 27 36 ... 74 23 30]
[32.35368444 32.92063212 35.38912712 ... 34.50003825 33.00078873
 32.9291931 ]
20.89266347858259
[63 42 22 ... 31 15 70]
[32.93441989 34.84690428 35.03246971 ... 32.38146096 34.49468374
 34.92205111]
20.83517527558916
[28 15 74 ... 50 51 44]
[34.71366264 32.84117482 34.66562872 ... 32.13438061 34.56426205
 36.37956349]
20.899447553070125
[72 35  2 ... 44 31 20]
[34.21684293 32.24253524 33.28562864 ... 34.3070438  34.17798924
 34.2830595 ]
20.79043667496869
CV::::20.88483940751075


In [ ]:
a = torch.sigmoid(torch.tensor(train_df['embbeding_swin_large_patch4_window12_384_0'].values))*100
idx_0_10 = (0<train_df['Pawpularity']) & (train_df['Pawpularity']<10)y_val

In [36]:
import seaborn as sns

sns.distplot(
    a[], bins=100, color='#123456', label='data',
    kde=False,
    rug=False
)

SyntaxError: invalid syntax (847822051.py, line 4)

In [ ]:
sns.distplot(
    train_df['Pawpularity'], bins=100, color='#123456', label='data',
    kde=False,
    rug=False
)